POST  http://localhost:3003/user/signup
Content-Type: application/json

{

    "name": "Leonardo",
    "email": "leo@gmail.com",
    "password": "16515dasv",
    "role":"admin"
}

###
//login
POST  http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "leo@gmail.com",
    "password": "16515dasv"
    
}


###
POST  http://localhost:3003/passeio/criar
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ0MDQ1M2VlLThkY2YtNDI2Mi1hNDcwLTg3NzljOGQ2ZWFlZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NTM1ODMxMiwiZXhwIjoxNjY1MzYxOTEyfQ.8eIui5ooM20WRnsco4uXz6eW5AEkaVa0uE8ZEK5VPyg

{
    "data_agendamento": "10/10/2022",     
    "duracao": 30,
    "latitude": -23.44353,
    "longitude": -46.50768,
    "pets": ["Billy","Max"],
    "hora_inicio": "11:03" 
    
    
    
}






###
get  http://localhost:3003/passeio?data=10/10/2022&sort=duracao&order=asc&page=1&size=10
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ0MDQ1M2VlLThkY2YtNDI2Mi1hNDcwLTg3NzljOGQ2ZWFlZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NTM0NjM0NCwiZXhwIjoxNjY1MzQ5OTQ0fQ.Am6VlN5M8VzeNce27CXC5w6oSBOQcWNHclXva7D1gd8




###
get  http://localhost:3003/passeio/all?sort=preco&order=asc&page=1&size=10
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ0MDQ1M2VlLThkY2YtNDI2Mi1hNDcwLTg3NzljOGQ2ZWFlZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NTM0NjM0NCwiZXhwIjoxNjY1MzQ5OTQ0fQ.Am6VlN5M8VzeNce27CXC5w6oSBOQcWNHclXva7D1gd8



###
POST   http://localhost:3003/passeio/start/1fdd4c49-6067-42aa-bd7b-67e6ef5cc3b3
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ0MDQ1M2VlLThkY2YtNDI2Mi1hNDcwLTg3NzljOGQ2ZWFlZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NTM0NjM0NCwiZXhwIjoxNjY1MzQ5OTQ0fQ.Am6VlN5M8VzeNce27CXC5w6oSBOQcWNHclXva7D1gd8



###
POST   http://localhost:3003/passeio/stop/1fdd4c49-6067-42aa-bd7b-67e6ef5cc3b3
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ0MDQ1M2VlLThkY2YtNDI2Mi1hNDcwLTg3NzljOGQ2ZWFlZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NTM0NjM0NCwiZXhwIjoxNjY1MzQ5OTQ0fQ.Am6VlN5M8VzeNce27CXC5w6oSBOQcWNHclXva7D1gd8



###
GET    http://localhost:3003/passeio/show/1fdd4c49-6067-42aa-bd7b-67e6ef5cc3b3
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ0MDQ1M2VlLThkY2YtNDI2Mi1hNDcwLTg3NzljOGQ2ZWFlZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2NTM0NjM0NCwiZXhwIjoxNjY1MzQ5OTQ0fQ.Am6VlN5M8VzeNce27CXC5w6oSBOQcWNHclXva7D1gd8